spring.application.name=product-service

server.port=8082
server.shutdown=graceful

spring.lifecycle.timeout-per-shutdown-phase=30s

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5432/product-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

management.endpoints.web.exposure.include=health,info,metrics,loggers,env
management.endpoint.health.show-details=always

